if(EXISTS "/mnt/c/Users/Janine/Desktop/Semester 1/HPC/HPC/src/tests/tests[1]_tests.cmake")
  include("/mnt/c/Users/Janine/Desktop/Semester 1/HPC/HPC/src/tests/tests[1]_tests.cmake")
else()
  add_test(tests_NOT_BUILT tests_NOT_BUILT)
endif()
